plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'co.elastic.clients:elasticsearch-java'
    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
}
