version: "3.8"

services:
  localstack:
    image: localstack/localstack:2.3.2
    container_name: localstack-lambda-poc
    ports:
      - "4566:4566"         # LocalStack Gateway
      - "4510-4559:4510-4559" # External services port range
    environment:
      - SERVICES=s3,lambda,iam,logs,stepfunctions
      - DEBUG=0
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./build/libs:/opt/code/localstack/lambda-jars"
